n, m = map(int, input().split())
A = list(map(int, input().split()))
B = list(map(int, input().split()))
A = set(A)
B = set(B)
A2 = A.difference(B)
B2 = B.difference(A)
C = A2.union(B2)
print(len(C))